<?php $this->headTitle('Adicionando Usuário'); ?>
<div class="content-wrapper">
    <?= $this->partial('flash-messages'); ?>
    <section class="content-header">
        <h1>Adicionando Usuário</h1>
        <ol class="breadcrumb">
            <li><a href="<?= $this->url('admin'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="<?= $this->url('admin-user'); ?>">Usuários</a></li>
            <li class="active">Adicionando Usuário</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h4>Informe os detalhes do usuário</h4>
                    </div>
                    <div class="box-body">
                        <?= $this->render('user/admin/user/form.phtml', [
                            'form' => $this->form,
                            'errorMessages' => $this->errorMessages,
                            'edit' => false
                        ]); ?>
                    </div>
                </div>
            </div>

        </div>
    </section>
</div>