<?php $this->headTitle('Login'); ?>
<div class="col-md-12 text-center">
    <?= $this->partial('flash-messages'); ?>
</div>
<div class="table-wrapper">
    <div class="table-row">
        <div class="table-cell text-center">
            <div class="login i-block">
                <div class="content-box">
                    <div class="biggest-box">
                        <img src="/img/logo.png" alt="Logo Neolaser">
                    </div>
                    <div class="big-box text-left login-form">
                        <h2 class="zero-m text-uppercase text-center">Login</h2>
                        <form role="form" method="post" enctype="application/x-www-form-urlencoded">
                            <div class="form-group">
                                <input id="email" type="email" name="email" class="form-control material"
                                       placeholder="Email">
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" class="form-control material" id="password"
                                       placeholder="Senha">
                            </div>
                            <button type="submit" class="btn btn-block btn-info text-uppercase waves">Login</button>
                        </form>
                        <a class="d-block small mt-3" href="<?= $this->url('password-recovery'); ?>">
                            Esqueci minha senha
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/bower_components/Waves/dist/waves.min.js"></script>
<script>
    //Waves effect on buttons
    Waves.attach('.waves', ['waves-float']);
    Waves.init();
</script>

<?php if (! empty($this->errorMessages)) : ?>
    <script>
        swal("Oops...", "Dados de login inválidos.", "error");
    </script>
<?php endif;
