<?php $this->headTitle('Erro na recuperação de senha'); ?>
<div class="container">
    <div class="col-md-12 text-center">
        <br/><br/>
        <a href="/">
            <img src="/img/logo.png">
        </a>
        <br/><br/>
    </div>
</div>

<br clear="all"/><br/>

<div class="container">
    <div class="col-md-12">
        <?= $this->partial('flash-messages'); ?>
    </div>
</div>

<br clear="all"/><br/><br/><br/><br/><br/><br/><br/><br/><br/>