<img src="<?php echo $this->serverUrl(); ?>/img/logo.png">
<br /><br />
Olá, <?php echo $this->name; ?>!
<br /><br />
Recentemente você solicitou a recuperação de sua senha, para prosseguir clique no link abaixo:

<br />
<a href="<?php echo $this->serverUrl() . $this->recoveryLink; ?>">
    <?php echo $this->serverUrl() . $this->recoveryLink; ?>
</a>
<br />
<br />
Este e-mail é gerado automaticamente, não o responda. Se você não solicitou a alteração, ignore este e-mail. Sua senha permanece a mesma já utilizada.