<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Neodent - Redefinição de senha</title>
</head>

<body bgcolor="#f9f9f9">

<table style="margin:0 auto;" align="center" border="0" cellpadding="0" cellspacing="0" width="100%" height="100%"
       bgcolor="#f8f7f8">
    <tr>
        <td width="100%" height="100%">

            <table style="margin:0 auto; font-family: Arial, Helvetica, sans-serif; font-size: 16px; line-height: normal; color: #000000;"
                   align="center" border="0" cellpadding="0" cellspacing="0" width="700" bgcolor="#f8f7f8">
                <tbody>
                <tr>
                    <td>
                        <div style="width: 100%; height: 80px;">&nbsp;</div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div style="float: left;">
                            <a href="<?= $this->serverUrl(); ?>" title="Neodent" style="text-decoration: none;">
                                <img src="<?= $this->serverUrl(); ?>/img/neodent-logo-email.png" alt="Neodent" border="0">
                            </a>
                        </div>
                        <div style="float: right; margin: 8px 0 0 0;">
                            <a href="<?= $this->serverUrl(); ?>" title="Neodent"
                               style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #7B1D6E; font-weight: bold; text-decoration: none; margin: 0; padding: 0;">Neodent
                                Cursos</a>
                        </div>
                        <div style="clear: both;"></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div style="width: 100%; height: 10px;">&nbsp;</div>
                    </td>
                </tr>
                <tr>
                    <td bgcolor="#ffffff">
                        <div style="margin: 85px 100px 50px 100px;">
                            <p style="font-family: Arial, Helvetica, sans-serif; font-size: 32px; color: #7B1D6E; font-weight: bold; margin: 0; padding: 0;">
                                Redefina sua senha</p>

                            <div style="width: 100%; height: 1px; background: #c4c4c4; margin: 35px 0 40px 0;"></div>

                            <p style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: normal; line-height: 26px; margin: 0; padding: 0;">
                                Olá, <?= $this->name; ?>.
                                <br><br>
                                Recentemente você solicitou a recuperação de sua senha.
                                <br><br>
                                Por motivo de segurança, não temos condições de lhe mostrar sua senha antiga. Por isso,
                                possibilitamos que você faça o cadastro de uma nova senha. Basta clicar no botão
                                abaixo e redefinir sua senha de acesso:
                                <br><br>
                            </p>

                            <a href="<?= $this->serverUrl() . $this->recoveryLink; ?>"
                               title="Redefinir senha"
                               style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #ffffff; font-weight: bold; text-decoration: none; margin: 0; padding: 15px 0 0 0; background: #7B1D6E; border-radius: 5px; display: block; margin: 0 auto; width: 335px; height: 35px; text-align: center;">Redefinir
                                senha</a>

                            <div style="width: 100%; height: 40px;">&nbsp;</div>

                            <p style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: normal; line-height: 26px; margin: 0; padding: 0;">
                                Caso o link não abra, copie o endereço abaixo e cole no seu navegador:
                                <br><br>
                                <a href="<?= $this->serverUrl() . $this->recoveryLink; ?>"
                                   style="color: #7B1D6E; text-decoration: none;">
                                    <?= $this->serverUrl() . $this->recoveryLink; ?>
                                </a>
                            </p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div style="width: 100%; height: 20px;">&nbsp;</div>

                        <p style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #000000; font-weight: normal; line-height: 19px; margin: 0; padding: 0;">
                            Esta mensagem foi enviada automaticamente, por favor não a responda. Caso não tenha sido
                            você que solicitou a restauração da senha, ignore este e-mail, sua senha permanecerá sem
                            modificação.</p>

                        <div style="width: 100%; height: 80px;">&nbsp;</div>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
</table>
</body>
</html>