<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Neodent', 'append')->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta name="robots" content="all,nofollow">
        <meta name="googlebot" content="noindex,nofollow">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <meta name="msapplication-tap-highlight" content="no"/>

        <?= $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ])
            ->appendStylesheet($this->basePath('css/admin/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('font/font-awesome/css/font-awesome.min.css'))
            ->appendStylesheet($this->basePath('css/admin/AdminLTE.css'))
            ->appendStylesheet($this->basePath('css/admin/skins/skin-neodent.css'))
            ->appendStylesheet(
                'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic'
            );
        ?>

        <?= $this->headScript()
            ->appendFile($this->basePath('js/admin/jquery.min.js'))
            ->appendFile($this->basePath('js/admin/bootstrap.min.js'));
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body class="hold-transition login-page">
        <div class="col-md-12 text-center">
            <?= $this->partial('flash-messages'); ?>
        </div>
        <div class="login-box">
            <div class="login-logo">
                <a href="<?= $this->url('admin-login'); ?>">
                    <img src="/img/neodent-logo-branco.png" style="height: 60px;">
                </a>
            </div>
            <?= $this->content; ?>
        </div>
    </body>
</html>