<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no"/>
    <?= $this->headTitle('ZF Base', 'append')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ])
        ->prependStylesheet($this->basePath('css/admin/custom.css'))
        ->prependStylesheet($this->basePath('bower_components/morris.js/morris.css'))
        ->prependStylesheet($this->basePath('bower_components/morris.js/morris.css'))
        ->prependStylesheet($this->basePath('bower_components/jvectormap/jquery-jvectormap.css'))
        ->prependStylesheet($this->basePath(
            'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css'
        ))
        ->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
        ->prependStylesheet($this->basePath('css/admin/AdminLTE.css'))
        ->prependStylesheet($this->basePath('css/admin/ionicons.min.css'))
        ->prependStylesheet($this->basePath('font/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/admin/bootstrap.min.css'))
    ?>

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/jquery-mask-plugin.min.js'))
        ->prependFile($this->basePath('js/jquery-price-format.js'))
        ->prependFile($this->basePath('js/admin/demo.js'))
        ->prependFile($this->basePath('js/bootstrap-datepicker.pt-BR.min.js'))
        ->prependFile($this->basePath('js/admin/dashboard.js'))
        ->prependFile($this->basePath('js/admin/adminlte.min.js'))
        ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
        ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
        ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
        ->prependFile($this->basePath('js/sweet-alert.js'));
    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <?= $this->headScript()
        ->prependFile('https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js')
        ->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js')
    ?>
    <![endif]-->

</head>
<body>

<body class="hold-transition skin-purple sidebar-mini">
<div class="wrapper">
    <?php $user = $this->userIdentity(); ?>
    <?= $this->render('partials/admin/header.phtml', ['user' => $user]); ?>
    <?= $this->render('partials/admin/sidemenu.phtml', ['user' => $user]); ?>
    <?= $this->content; ?>
    <?= $this->render('partials/admin/sidemenu-right.phtml', ['user' => $user]); ?>
    <?= $this->render('partials/admin/footer.phtml', ['user' => $user]); ?>
</div>
</body>

<?= $this->inlineScript() ?>
<script>
    $.widget.bridge('uibutton', $.ui.button);
    $('.<?= $this->menuItem; ?>').addClass('active');
</script>
<?= $this->headScript()->setFile($this->basePath('js/admin/custom.js')); ?>
</html>
