<?php $this->headTitle('Recuperação de senha'); ?>

<div class="login-box-body">
    <p class="login-box-msg">Redefina sua senha</p>

    <form method="post" enctype="application/x-www-form-urlencoded">
        <div class="form-group has-feedback">
            <input type="password" name="password" class="form-control"
                   placeholder="Informe sua nova senha">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <?php if (isset($this->errorMessages['password'])) : ?>
                <br/>
                <?php foreach ($this->errorMessages['password'] as $errorMessage) : ?>
                    <?= $this->translate($errorMessage); ?><br/>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <div class="form-group has-feedback">
            <input type="password" name="password-confirmation" class="form-control"
                   placeholder="Confirme sua nova senha">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <?php if (isset($this->errorMessages['passwordConfirmation'])) : ?>
                <br/>
                <?php foreach ($this->errorMessages['passwordConfirmation'] as $errorMessage) : ?>
                    <?= $this->translate($errorMessage); ?><br/>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Alterar senha</button>
            </div>
        </div>
        <?php if (isset($this->errorMessages['invalidLogin'])) : ?>
            <br/>
            <div class="alert alert-danger">
                <?= $this->translate($this->errorMessages['invalidLogin']); ?><br/>
            </div>
        <?php endif; ?>
    </form>
    <a href="<?= $this->url('admin-login'); ?>">Retornar ao login</a><br>
</div>