<?php $loggedUser = $this->userIdentity(); ?>
<header class="main-header">
    <a href="<?= $this->url('admin'); ?>" class="logo">
        <img src="/img/neodent-logo-branco.png" style="height: 40px;">
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="/files/avatar/<?= $loggedUser['id']; ?>/<?= $loggedUser['avatar']; ?>"
                             class="user-image" alt="User Image">
                        <span class="hidden-xs"><?= $loggedUser['name']; ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="/files/avatar/<?= $loggedUser['id']; ?>/<?= $loggedUser['avatar']; ?>"
                                 class="img-circle" alt="User Image">
                            <p>
                                <?= $loggedUser['name']; ?>
                                <small><?= $this->translate('Last login'); ?>:
                                    <?php if ($loggedUser['previous_last_login'] instanceof DateTime) : ?>
                                        <?= $loggedUser['previous_last_login']->format('d/m H:i'); ?>
                                    <?php endif; ?>
                                </small>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="<?= $this->url('admin-user', ['action' => 'profile']); ?>"
                                   class="btn btn-default btn-flat"><?= $this->translate('Profile'); ?>
                                </a>
                            </div>
                            <div class="pull-right">
                                <a href="<?= $this->url('admin-logout'); ?>" class="btn btn-default btn-flat">
                                    <?= $this->translate('Logout'); ?>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>